branches:
  only:
  - master
  - "/^v[0-9].*$/"
language: python
python:
- '3.6'
install:
- pip install --upgrade pip
- pip install -r requirements.txt
dist: trusty
sudo: required
services:
- postgresql
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
before_script:
- psql -U postgres -d travis -c "create extension postgis"
- mv configs/local_settings.py.travis committeeoversight/local_settings.py
script:
- python manage.py migrate
- pytest
notifications:
  slack:
    secure: WZE+shuIOGZGq+jBiM8AnsQH9uDmJ5utr3haTUh4bJuZyaE7ObzK3s4BJw5YUY9gaPu5X8pYGtD77Cz2Q+WwWeIOPnFGa7597n7aACONHE2kRr+gsDct+20tNnlYEgj1DykPYTtQ4SxgVR9aMl6+H9qr62nMWL2oOfPVhDe6ELMUdFkjsnCtKMUXUCc/Q60p4MhS9oh15gOZivrj/FDBxcqwdToXoDfXI5QkV6u620JhS/lFHGDk6vNllENsjuGh/pPNgXUY9WenaCWjS16lfeZhNP37mjTr790ET9ZtkS/dnx0A7O6t0fcgeUruV7jr25Z337RUtSBeUdWQRV2k7+z3vEWTIidJ+YacqtVUArCfBKr7mes5ADsMlLiEOcREBvQXdQ0osHiFo5vHXSjlEs++10TWvX/2SCiT6gW2x6LwdoX6lWw5KE3Yq8XySN/nxdD1wdRwjF3LDzKJmuZaa5O5VW0w7Ui7cXc89zQ/l5qAOH2Fh6wrYPqpbOS9dFsH/+z4ZtqFfbbPHaOMMGsOEmWI1pR/+K5w0MvzXTUcaYSit6F3C+aqlpWm2JHEWEJR6doH6mDYMxnnj/mqgVxh4+oCWFiECFgw+X3+ToGkSOAifudBZEA+GUKEfR1iCSRDbACFOsAOSbPzB49G4Tl/WtGk1VoQInZUTBSOna+TZro=
deploy:
  - provider: codedeploy
    access_key_id: AKIAJNYGDLOJKHOUWCAA
    secret_access_key:
      secure: OLO4aPTsLQi6ldlm17puLgSrosKDTVHIUYkGo4tp0rzRYdPxV/pmbvezD5/N9FEfNDLFhXSbFlRNbhdmXkLSeV+6s8nDmWz22yyItl7kvX9sDmK70U9nMZjH/eFgVKB0hCt5f7T7MzUTyycrj4cHj5qls/bge7v4MXi0CG8eeOGPi/pCM1PLUz3tOFzwcCP8O5iLVNvaDVPWIZ83zQzmspu29D38e2BJORAXH8FqYdJiWcYdge68oFzeouEelJFCswbQbKsl85r4ney8JwPgLatyD38wbn4O+dFO7cQKiEq3zWevT//7Im7n1y5AblgbiWSRqeW9YE3ldtAPOi9riMmxjHITqSdB/K1HyYGbeXg0SYYWzn8vfZMWF2Pj5eb8AhsSPSczLxUFrc4rgkvGmQO2WrvNf2ZxGmYzcU3cW/YByia9wL2tZLtn/4EZsLaxvBguhf9Np+4hwQa3Ycn8c8G14BYXFEkQo5ppmuKDFVW4jNU/ublMRTHLV1YuMVULR9t08IXMb60Uz8ue1QGevogPALczuxI9AQrIUDIwvS0YvRFEJ6Rlqhnq6UmkdEkOAvoWyd8F9Z2foi5Bzs3Z2Ns7J7wXAKn9+3Ws/TbvqfEdx2Kznx253lFtxcaz1i57vtegS43DsN2PwLqTPgoPB20n0bmh6RvAvvRjlesAJ3A=
    revision_type: github
    application: committee-oversight
    deployment_group: staging
    on:
      branch: master
deploy:
  - provider: codedeploy
    access_key_id: AKIAJNYGDLOJKHOUWCAA
    secret_access_key:
      secure: OLO4aPTsLQi6ldlm17puLgSrosKDTVHIUYkGo4tp0rzRYdPxV/pmbvezD5/N9FEfNDLFhXSbFlRNbhdmXkLSeV+6s8nDmWz22yyItl7kvX9sDmK70U9nMZjH/eFgVKB0hCt5f7T7MzUTyycrj4cHj5qls/bge7v4MXi0CG8eeOGPi/pCM1PLUz3tOFzwcCP8O5iLVNvaDVPWIZ83zQzmspu29D38e2BJORAXH8FqYdJiWcYdge68oFzeouEelJFCswbQbKsl85r4ney8JwPgLatyD38wbn4O+dFO7cQKiEq3zWevT//7Im7n1y5AblgbiWSRqeW9YE3ldtAPOi9riMmxjHITqSdB/K1HyYGbeXg0SYYWzn8vfZMWF2Pj5eb8AhsSPSczLxUFrc4rgkvGmQO2WrvNf2ZxGmYzcU3cW/YByia9wL2tZLtn/4EZsLaxvBguhf9Np+4hwQa3Ycn8c8G14BYXFEkQo5ppmuKDFVW4jNU/ublMRTHLV1YuMVULR9t08IXMb60Uz8ue1QGevogPALczuxI9AQrIUDIwvS0YvRFEJ6Rlqhnq6UmkdEkOAvoWyd8F9Z2foi5Bzs3Z2Ns7J7wXAKn9+3Ws/TbvqfEdx2Kznx253lFtxcaz1i57vtegS43DsN2PwLqTPgoPB20n0bmh6RvAvvRjlesAJ3A=
    revision_type: github
    application: committee-oversight
    deployment_group: production
    on:
      tags: true
