version: '2.4'

services:
  dbload:
    container_name: committeeoversight-dbload
    image: committeeoversight:latest
    depends_on:
      postgres:
        condition: service_healthy
      app:
        condition: service_healthy
    volumes:
      - .:/app
      - ${PWD}/committeeoversight/local_settings.example.py:/app/committeeoversight/local_settings.py
    command: 'true'

  postgres:
      command: pg_restore -C -j4 --no-owner -U postgres -d hearings /app/hearings.dump

  app:
    command: >
      bash -c "python manage.py migrate &&
      python manage.py load_cms_content &&
      python manage.py load_committeeratings &&
      python manage.py loaddata hearingcategorytype"
