version: '2.4'

services:
  dbload-dump:
    container_name: committeeoversight-dbload-dump
    image: mdillon/postgis:10
    depends_on:
      - app
      - postgres
    volumes:
      - .:/app
      - ${PWD}/committeeoversight/local_settings.example.py:/app/committeeoversight/local_settings.py
    command: pg_restore -C -j4 --no-owner -U postgres -d hearings -h postgres -p 5432 /app/hearings.dump

  dbload-fixtures:
    container_name: committeeoversight-dbload-fixtures
    image: committeeoversight:latest
    volumes:
      - .:/app
      - ${PWD}/committeeoversight/local_settings.example.py:/app/committeeoversight/local_settings.py
    command: >
      bash -c "python manage.py migrate &&
      python manage.py loaddata congress &&
      python manage.py loaddata hearingcategorytype &&
      python manage.py load_committeeratings &&
      python manage.py createcachetable"
