# Generated by Django 2.1.2 on 2019-02-06 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171005_2028'),
        ('committeeoversightapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_id', models.IntegerField(blank=True, null=True)),
                ('lugar_name', models.CharField(blank=True, max_length=200, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='witnessdetails',
            name='retired',
            field=models.BooleanField(default=False),
        ),
    ]
