# Generated by Django 2.1.2 on 2018-11-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committeeoversightapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='witnessdetails',
            name='retired',
            field=models.BooleanField(default=False),
        ),
    ]
