# Generated by Django 2.1.2 on 2019-04-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committeeoversightapp', '0002_auto_20190206_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='witnessdetails',
            name='witnessdetails',
        ),
        migrations.AddField(
            model_name='witnessdetails',
            name='retired',
            field=models.BooleanField(default=False),
        ),
    ]
