# Generated by Django 2.1.8 on 2019-09-11 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committeeoversightapp', '0005_staticpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydetailpage',
            old_name='body',
            new_name='description',
        ),
        migrations.AddField(
            model_name='categorydetailpage',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='committeeoversightapp.HearingCategoryType'),
        ),
    ]
