# Generated by Django 2.1.8 on 2019-09-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committeeoversightapp', '0006_auto_20190911_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydetailpage',
            old_name='description',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='categorydetailpage',
            old_name='category',
            new_name='detail_object',
        ),
    ]
