# Generated by Django 2.1.12 on 2019-09-11 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committeeoversightapp', '0007_auto_20190911_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydetailpage',
            name='detail_object',
            field=models.ForeignKey(help_text='Select a category for this page.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='committeeoversightapp.HearingCategoryType'),
        ),
    ]
