# Generated by Django 2.1.12 on 2019-09-11 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committeeoversightapp', '0008_auto_20190911_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydetailpage',
            old_name='detail_object',
            new_name='category',
        ),
    ]
