# Generated by Django 2.1.12 on 2019-09-19 20:14

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171005_2028'),
        ('committeeoversightapp', '0010_landingpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeOrganization',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core.organization',),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='body',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
