# Generated by Django 2.1.12 on 2019-09-17 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committeeoversightapp', '0010_landingpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=100)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committeeoversightapp.Committee')),
            ],
        ),
        migrations.CreateModel(
            name='Congress',
            fields=[
                ('identifier', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='committeerating',
            name='congress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committeeoversightapp.Congress'),
        ),
    ]
