# Generated by Django 2.1.12 on 2019-09-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committeeoversightapp', '0011_add_committeerating'),
        ('committeeoversightapp', '0011_auto_20190919_1514'),
    ]

    operations = [
    ]
