# Generated by Django 2.1.12 on 2019-09-25 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('committeeoversightapp', '0013_add_committeedetailpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
    ]
