# Generated by Django 2.1.14 on 2019-11-11 22:46

import committeeoversightapp.models
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('committeeoversightapp', '0016_hearinglistpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareCommitteesOverCongresses',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=(committeeoversightapp.models.ResetMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='CompareCurrentCommittees',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=(committeeoversightapp.models.ResetMixin, 'wagtailcore.page'),
        ),
    ]
