# Generated by Django 2.1.14 on 2019-11-11 22:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('committeeoversightapp', '0017_comparecommitteesovercongresses_comparecurrentcommittees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompareCommitteesOverCongresses',
            new_name='CompareCommitteesOverCongressesPage',
        ),
        migrations.RenameModel(
            old_name='CompareCurrentCommittees',
            new_name='CompareCurrentCommitteesPage',
        ),
    ]
