# Generated by Django 2.1.14 on 2019-11-12 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committeeoversightapp', '0018_auto_20191111_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Congress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='committeerating',
            name='rating',
        ),
        migrations.AddField(
            model_name='committeerating',
            name='investigative_oversight_hearings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='committeerating',
            name='policy_legislative_hearings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='committeerating',
            name='total_hearings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='committeerating',
            name='congress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committeeoversightapp.Congress'),
        ),
    ]
