# Generated by Django 2.1.14 on 2019-11-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committeeoversightapp', '0019_auto_20191112_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeerating',
            name='chp_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
