# Generated by Django 2.1.14 on 2019-11-25 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committeeoversightapp', '0020_committeerating_chp_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeerating',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committeeoversightapp.CommitteeOrganization'),
        ),
    ]
