# Generated by Django 2.1.15 on 2020-04-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committeeoversightapp', '0022_hearingevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='congress',
            name='length',
            field=models.IntegerField(default=668),
        ),
    ]
