# Generated by Django 2.1.15 on 2020-04-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committeeoversightapp', '0023_committeedetailpage_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeedetailpage',
            name='display_name',
            field=models.TextField(blank=True, help_text="Use this field to change the way a committee's name is displayed. If left empty, the name will not be modified.", null=True),
        ),
    ]
