# Generated by Django 2.1.15 on 2020-04-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committeeoversightapp', '0024_auto_20200406_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='congress',
            name='inactive_days',
            field=models.IntegerField(default=61),
        ),
    ]
