# Generated by Django 2.1.15 on 2020-04-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committeeoversightapp', '0026_auto_20200413_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='congress',
            name='footnote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
